IR_PIN = 17

SERVO_SORT_PIN = 18
SERVO_RELEASE_PIN = 19

CONF_THRESHOLD = 0.7
COOLDOWN = 3

K = 80

PRICE_PER_KG = {
    "CLEAR_BOTTLES": 10,
    "OPAQUE_BOTTLES": 3,
    "GLASSES_BOTTLES": 0.5,
    "STEEL_CAN": 2,
    "ALUMINUM_CANS": 40
}

GRAM_PER_ML = {
    "CLEAR_BOTTLE": 0.033,
    "OPAQUE_BOTTLE": 0.08,
    "GLASSES_BOTTLE": 0.4,
    "STEEL_CAN": 0.17,
    "ALUMINUM_CAN": 0.033
}

SCORE_PER_GRAM = {
    "CLEAR_BOTTLE": 0.8,
    "OPAQUE_BOTTLE": 0.24,
    "GLASSES_BOTTLE": 0.04,
    "STEEL_CAN": 0.16,
    "ALUMINUM_CAN": 3.2
}

K = 80