spring.data.mongodb.host=${MONGODB_HOST:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=iotdb
server.port=8070

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# API Key Security for IoT Devices
sbay.device.secret=${DEVICE_SECRET}

# Debug logging for web requests
logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true
spring.codec.log-request-details=true
